default: &default
  adapter: postgresql
  encoding: unicode
  username: "mandakeru"
  password: "qweqwe123"

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: for-craft_development

test:
  <<: *default
  database: for-craft_test


production:
  <<: *default
  database: for-craft_production
  username: for-craft
  password: <%= ENV['FOR-CRAFT_DATABASE_PASSWORD'] %>
